name: AVOS Cloud 开放资源
description: AVOS Cloud 的非产品类公开资源
author: AVOS Cloud

markdown: kramdown

exclude: [README.md, Gemfile, Gemfile.lock, LICENSE]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"